name: CI

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 9-21 * * *' # Runs every hour between 9am and 9pm
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies to run get_data.py
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run send_to_telegram.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python send_to_telegram.py

   # Add new files in data folder, commit along with other modified files, push
      - name: Commit files
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"
          git add .
          git commit -am "GH ACTION Headlines $(date)"
          git push origin main
        env:
          REPO_KEY: ${{secrets.GITHUB_TOKEN}}
          username: github-actions